# Site
name: "Ryan Padilha"
title: "Ryan Padilha"
description: "With 16+ years of experience, I excel in digital transformation, cloud computing, and modern tech solutions. Proficient in AWS, Java, Python, and microservices architecture, I lead cross-functional teams, driving rapid growth. Passionate about R&D, problem-solving, and continuous learning, I thrive on challenges and consistently exceed goals."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
#baseurl: /blog
google_analytics: ''
disqus: 'ryanpadilha'
#mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ryanpadilha:
    name: Ryan Padilha
    display_name: Ryan Padilha
    gravatar: a27132d9f4553243e4359ad6341082f2
    email: ryan.padilha@gmail.com
    web: https://www.linkedin.com/in/ryanpadilha
    description: "Solutions Architect at Banking Industry"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [Gemfile, Gemfile.lock]
